sleepSeconds : 3
isContinue : true
epochFormatter : dd-MM-yyyy HH:mm:ss
processHealthStatusConf:
  processMonCommand : ps -ef | grep -v grep | grep process_name
  processList :
    - calculator
    - gedit
fileHealthStatusConf :
  monFiles:
    - file : /home/lgmdev/MeosarLog/Meosar_Backend_2.log
      permissibleUpdateWindowInSec : 5
    - file : /home/lgmdev/MeosarLog/Meosar_Backend.log
      permissibleUpdateWindowInSec: 5

systemDHealthStatusConf:
  systemMonCommand : systemctl status service_name
  serviceList :
    - postgresql.service
    - postgresql@14-main.service
diskHealthStatusConf :
  diskMonCommand : df -k

showEpoch : true
showEpochKeyWithStatus : true
showKeyWithStatus : true
healthStatusLogArea : /home/lgmdev/MeosarLog/